//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.25 at 03:16:12 PM GMT-03:00 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://brejaonline.com.br/pessoa/v1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package br.com.geladaonline;
